# Generated by Django 4.0.10 on 2024-08-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Working_Room'), (2, 'Sleeping_Room')], null=True),
        ),
    ]
